### ISSUE TITLE
您好，您的readme.md里写错了

### ISSUE THREAD

**Issue by codelovercc** [bill-wangwang/python_scrapy_bank#1]
谢谢您的分享
我尝试按照里面说操作，发现执行顺序实际上是
    - scrapy crawl 1_get_bank_type
    - scrapy crawl 3_get_prov
    - scrapy crawl 2_get_city
    - scrapy crawl 4_get_bank

按照文档里面的顺序执行scrapy crawl 2_get_city 时得不到任何输出，请修正

**Comment by bill-wangwang** [comment]
谢谢提醒，你应该是对的，思路应该是先获取 所有银行，然后获取这个银行下的所有省份，再到城市，最后才是具体的支行
